# Generated by Django 2.1.5 on 2023-03-23 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
