# Generated by Django 2.2.28 on 2023-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230303_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantName',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
